insert into pocket.pokemon_raw(pokemon_name,color,type_id_1,type_id_2,region,egg_id_1,egg_id_2,pre_evo)
values
('Mareep','White','Electric','','Johto','Monster','Field',''),
('Flaaffy','Pink','Electric','','Johto','Monster','Field','Mareep'),
('Ampharos','Yellow','Electric','','Johto','Monster','Field','Flaaffy'),
('Dratini','Blue','Dragon','','Kanto','Water 1','Dragon',''),
('Dragonair','Blue','Dragon','','Kanto','Water 1','Dragon','Dratini'),
('Dragonite','Brown','Dragon','Flying','Kanto','Water 1','Dragon','Dragonair'),
('Riolu','Blue','Fighting','','Sinnoh','Undiscovered','',''),
('Lucario','Blue','Fighting','Steel','Sinnoh','Field','Human-Like','Riolu'),
('Zorua','Gray','Dark','','Unova','Field','',''),
('Zoroark','Gray','Dark','','Unova','Field','','Zorua'),
('Zeraora','Yellow','Electric','','Alola','Undiscovered','',''),
('Torchic','Red','Fire','','Hoenn','Field','',''),
('Combusken','Red','Fire','Fighting','Hoenn','Field','','Torchic'),
('Blaziken','Red','Fire','Fighting','Hoenn','Field','','Combusken'),
('Magikarp','Red','Water','','Kanto','Water 2','Dragon',''),
('Gyarados','Blue','Water','Flying','Kanto','Water 2','Dragon','Magikarp'),
('Sprigatito','Green','Grass','','Paldea','Field','Grass',''),
('Floragato','Green','Grass','','Paldea','Field','Grass','Sprigatito'),
('Meowscarada','Green','Grass','Dark','Paldea','Field','Grass','Floragato'),
('Eevee','Brown','Normal','','Kanto','Field','',''),
('Vaporeon','Blue','Water','','Kanto','Field','','Eevee'),
('Jolteon','Yellow','Electric','','Kanto','Field','','Eevee'),
('Flareon','Red','Fire','','Kanto','Field','','Eevee'),
('Espeon','Purple','Psychic','','Johto','Field','','Eevee'),
('Umbreon','Black','Dark','','Johto','Field','','Eevee'),
('Leafeon','Green','Grass','','Sinnoh','Field','','Eevee'),
('Glaceon','Blue','Ice','','Sinnoh','Field','','Eevee'),
('Sylveon','Pink','Fairy','','Kalos','Field','','Eevee'),
('Ralts','White','Psychic','Fairy','Hoenn','Human-Like','Amorphous',''),
('Kirlia','White','Psychic','Fairy','Hoenn','Human-Like','Amorphous','Ralts'),
('Gardevoir','White','Psychic','Fairy','Hoenn','Human-Like','Amorphous','Kirlia'),
('Gallade','White','Psychic','Fighting','Sinnoh','Human-Like','Amorphous','Kirlia')